### ISSUE TITLE
language selection bug

### ISSUE THREAD

**Issue by AlphaHot** [github/issue-labeler#10]
![image](https://user-images.githubusercontent.com/58410019/79047828-93e9bf00-7c32-11ea-9686-21ecdab5c1bb.png)

**Comment by AlphaHot** [comment]
Sorry, I just don't know where to write about this issue

**Comment by stephanmiehe** [comment]
👋 @AlphaHot it looks like this issue does not related to `issue-labeler`. I'm going to go ahead and close this issue. Please raise the issue against the appropriate repository. If you're running into a bug with the GitHub platform, I'd recommend reaching out to [GitHub support ](https://support.github.com/)
