### ISSUE TITLE
Match whole word

### ISSUE THREAD

**Issue by johanrin** [github/issue-labeler#16]
Is it possible to match a word?

For instance, I have this rule defined in my `.github/labeler.yml` file:
```
SEC:
  - "(SEC)"
```

if I have the following URL in the body:
`https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html`

It will apply the label `SEC` on the issue, which is normal.

But how can I restrict the rule to check only `(SEC)` with the parenthesis?

For instance
`Cloud Security (SEC)`

**Comment by stephanmiehe** [comment]
@johanrin `(` and `)` signal a capture group in regex land. If you want to include the parenthesis you'll want to add them escaped. Using `"(\(SEC\))"` should do the trick.

**Comment by johanrin** [comment]
Thanks @stephanmiehe for the idea.

It was almost that. I edited my rules and now it works!

```
SEC:
  - "(\\(SEC\\))"
```
