### ISSUE TITLE
Add a Default Label option.

### ISSUE THREAD

**Issue by vybhav72954** [github/issue-labeler#19]
There should be a default label option, which would be very helpful.

**Comment by FionnD** [comment]
You could try setting the regex to . which should trigger on any written content.

**Comment by ArmandAgopian** [comment]
Hi, after setting the regex to ., I still cannot set a default label. Here is an example:

`example-label:
  - '.'`

**Comment by IWANABETHATGUY** [comment]
Hi guys, https://github.com/github/issue-labeler/blob/e24a3eb6b2e28c8904d086302a2b760647f5f45c/src/main.ts#LL201C3-L213C4. I found this line, so if you want to match wildcard you should use /.*/ instead.

**Comment by stephanmiehe** [comment]
Added to docs https://github.com/github/issue-labeler/blob/master/README.md#label-all-issues
