### ISSUE TITLE
Auto select filter when clicking labels

### ISSUE THREAD

**Issue by LorenzoSapora** [github/issue-labeler#51]
Situation: I want to quickly add a single label to an existing issue. However, if I click labels, I have to then click the text filter to begin refining. Auto selecting the input would save some time.

Reproduce:
- Create issue
- Click Labels in right sidebar
- Click input
- Start typing

End goal:
- Create issue
- Click Labels in right sidebar
- Start typing

**Comment by LorenzoSapora** [comment]
![gh-labels](https://user-images.githubusercontent.com/25519274/183424888-76815a25-0d42-4ab8-88c0-b18c94a97015.gif)

**Comment by stephanmiehe** [comment]
👋  @LorenzoSapora this seems like a feature request for github.com. This repo is a GitHub Action for automating the labeling of repos. I'm going to go ahead and close this issue.
