### ISSUE TITLE
HttpError: Label does not exist (although it is defined for the project)

### ISSUE THREAD

**Issue by andthum** [github/issue-labeler#60]
Related issues #20, #32  
Related PRs #57

With issue-labeler version 2.5, I got `UnhandledPromiseRejectionWarning: HttpError: Label does not exist` warnings but the workflow passed and the PRs got labelled as expected (e.g. https://github.com/andthum/mdtools/pull/138, https://github.com/andthum/mdtools/actions/runs/4076674579/jobs/7024720065).

Now with issue-labeler version 2.6, I get `HttpError: Label does not exist` errors and the workflow fails, although the PRs still get labelled as expected (e.g. https://github.com/andthum/mdtools/pull/140, https://github.com/andthum/mdtools/actions/runs/4113712400/jobs/7100168530).

I think this behavior change was introduced with PR #57.

My questions:
1. Why does the warning (v2.5) / error (v2.6) pop up at all? The labels have been defined for the repository (https://github.com/andthum/mdtools/labels).
2. What do I have to do to fix the `HttpError: Label does not exist` error?

If this helps: My issue-labeler config file can be found [here](https://github.com/andthum/mdtools/blob/c88750c06a319d7dc66dab51c887e17fb2e48b01/.github/pr-labeler-config-v1.yml) and my issue-labeler workflow is defined [here](https://github.com/andthum/mdtools/blob/c88750c06a319d7dc66dab51c887e17fb2e48b01/.github/workflows/pr-labeler.yml).

@balazsorban44: If you have time and the required expertise, could you please help me out? Many thanks!

**Comment by balazsorban44** [comment]
https://github.com/github/issue-labeler/pull/59#discussion_r1093345415

The repo seems to get little attention (prev PR was only merged because I pinged someone on the team). I'm thinking to use my fork. :grin:

**Comment by andthum** [comment]
Thanks for your reply and your contributions to this project. Then I will wait for the new release and see if this fixes my issue.

I will close the issue for now and re-open if the issue persists in the upcoming release.
