### ISSUE TITLE
Labeler fails when issue body is empty

### ISSUE THREAD

**Issue by dokimiki** [github/issue-labeler#61]
The problem that is occurring is the same as in #33, but does not appear to have been fixed in the latest version.

translate by deepl.com

**Comment by iba-1** [comment]
This is very much needed as #57 is totally breaking this action, and @dokimiki #62 may indeed fix it, is there any way we can get your attention @stephanmiehe?

**Comment by stephanmiehe** [comment]
Hey folks, I'm on a cruise at the moment but will cut a new release next week when I'm back on keys
