### ISSUE TITLE
Warning: Unexpected input(s) 'include-body'

### ISSUE THREAD

**Issue by greg-finley** [github/issue-labeler#77]
VS Code and GitHub Actions both say I can't use `include-body`. I'm actually not sure if it's just a false warning or not.

https://github.com/sqlfluff/sqlfluff/blob/main/.github/workflows/add-issue-labels.yaml

https://github.com/sqlfluff/sqlfluff/actions/runs/5493261870/jobs/10011320794

<img width="881" alt="Screenshot 2023-07-08 at 8 22 17 AM" src="https://github.com/github/issue-labeler/assets/28961086/e1b0976c-0ff6-4875-a021-b2dbcd040b52">

**Comment by greg-finley** [comment]
The issue does get the "bigquery" label even though we only want to look at the issue title, which doesn't mention bigquery: https://github.com/sqlfluff/sqlfluff/issues/4957

**Comment by greg-finley** [comment]
Ah, I guess it's just an unreleased feature?

**Comment by stephanmiehe** [comment]
I've gone ahead and released v3.2 which includes this feature

**Comment by greg-finley** [comment]
Thanks!
